Name:			autoconf-archive
Version:		2011.09.17
Release:		%mkrel 1
Summary:		The Autoconf Macro Archive
Group:			Development/Other
License:		GPLv3+ with exceptions
URL:			http://www.gnu.org/software/autoconf-archive/
Source0:		ftp://ftp.gnu.org/gnu/autoconf-archive/%{name}-%{version}.tar.xz
BuildArch:		noarch
BuildRequires:		texinfo
Requires:		autoconf
Requires(post):		info
Requires(preun):	info
BuildRoot:		%{_tmppath}/%{name}-%{version}-%{release}-root

%description
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.

%prep
%setup -q

%build
%configure2_5x
%make

%install
rm -rf %{buildroot}
%makeinstall_std

# remove dir file which will be generated by /sbin/install-info
rm -f %{buildroot}%{_infodir}/dir

# document files are installed another location
rm -rf %{buildroot}%{_datadir}/%{name}

%clean
rm -rf %{buildroot}

%post
%_install_info %{name}.info

%preun
%_remove_install_info %{name}.info

%files
%defattr(-,root,root,-)
%doc AUTHORS COPYING* ChangeLog NEWS README TODO
%{_datadir}/aclocal/*.m4
%{_infodir}/autoconf-archive.info*

